stages:
- tests
- build
- deploy
- release

variables:
    FACTORY_PRODUCT_NAME: cadastre
    FACTORY_PACKAGE_NAME: qgis_cadastre
    FACTORY_PACKAGE_TYPE: plugin
    FACTORY_MANIFEST: ".lizcloud/factory.manifest"

check_tag:
  stage: tests
  only:
    - tags
  tags:
    - fabric
  script:
    - .lizcloud/check_tag.sh ${CI_COMMIT_REF_NAME}

build_3:
  stage: build
  script:
    - make -C .lizcloud -f factory.mk package
  environment:
    name: snap
  artifacts:
    paths:
      - ".lizcloud/factory.manifest"
  tags:
    - infrav3

deploy_snap_3:
  stage: deploy
  script:
    - $FACTORY_SCRIPTS/deploy-package $FACTORY_PACKAGE_NAME
  environment:
    name: snap
  tags:
    - infrav3

release_prod_3:
  stage: release
  script:
    - $FACTORY_SCRIPTS/release-package $FACTORY_PACKAGE_NAME
  environment:
    name: production
  when: manual
  only:
    - tags
  tags:
    - infrav3


build_2:
  stage: build
  script:
    - make  -C .lizcloud -f fabric.mk package
  environment:
    name: snap
  tags:
    - fabric

deploy_snap_2:
  stage: deploy
  script:
    - sudo -u fabric fab snap deploy:qgis3_cadastre,force=true
  environment:
    name: snap
  tags:
    - fabric

release_prod_2:
  stage: release
  script:
    - sudo -u fabric fab prod release:qgis3_cadastre
  environment:
    name: production
  when: manual
  only:
    - tags
  tags:
    - fabric

issues:
  stage: release
  allow_failure: true
  when: manual
  only:
    - tags
  script:
    # Lizmap-box
    - >
      curl
      --header 'Content-Type:application/json'
      --header "PRIVATE-TOKEN:${USER_TOKEN}"
      --data '{
      "id":70,
      "assignee_ids":[77],
      "labels":"qgis server",
      "title":"Nouvelle version '"${FACTORY_PRODUCT_NAME}"' : '"${CI_COMMIT_REF_NAME}"'",
      "description":"Il existe une nouvelle version '"${FACTORY_PRODUCT_NAME}"' : '"${CI_COMMIT_REF_NAME}"' 👍"}'
      --request POST https://projects.3liz.org/api/v4/projects/70/issues
    # Infra-doc
    - >
      curl
      --header 'Content-Type:application/json'
      --header "PRIVATE-TOKEN:${USER_TOKEN}"
      --data '{
      "id":7,
      "assignee_ids":[2],
      "labels":"SAAS Qgis,release,infra-v2",
      "title":"Nouvelle version '"${FACTORY_PRODUCT_NAME}"' : '"${CI_COMMIT_REF_NAME}"'",
      "description":"Il existe une nouvelle version '"${FACTORY_PRODUCT_NAME}"' : '"${CI_COMMIT_REF_NAME}"' 👍"}'
      --request POST https://projects.3liz.org/api/v4/projects/7/issues
    - >
      curl
      --header 'Content-Type:application/json'
      --header "PRIVATE-TOKEN:${USER_TOKEN}"
      --data '{
      "id":7,
      "assignee_ids":[5],
      "labels":"SAAS Qgis,release,infra-v3",
      "title":"Nouvelle version '"${FACTORY_PRODUCT_NAME}"' : '"${CI_COMMIT_REF_NAME}"'",
      "description":"Il existe une nouvelle version '"${FACTORY_PRODUCT_NAME}"' : '"${CI_COMMIT_REF_NAME}"' 👍"}'
      --request POST https://projects.3liz.org/api/v4/projects/7/issues
  tags:
    - factory
